# Generated by Django 5.2.7 on 2025-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Используется для входа в систему.",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
