# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Короткий заголовок сообщения (отображается в поле Subject).",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Тема не может быть пустой."
                            )
                        ],
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Основное содержимое письма в свободной форме.",
                        verbose_name="Текст письма",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("-created_at",),
                "permissions": (
                    ("view_all_messages", "Может просматривать все сообщения"),
                ),
            },
        ),
    ]
