# Generated by Django 5.2.7 on 2025-11-07 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                help_text="Основное содержимое письма в свободной форме.",
                verbose_name="Тело письма",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                help_text="Короткий заголовок сообщения (отображается в поле Subject).",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Тема не может быть пустой."
                    )
                ],
                verbose_name="Тема письма",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-created_at"], name="idx_msg_created_desc"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["subject"], name="idx_msg_subject"),
        ),
    ]
