# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("messages_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь-владелец шаблона сообщения.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["owner"], name="idx_message_owner"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-created_at"], name="idx_msg_created_desc"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["subject"], name="idx_msg_subject"),
        ),
    ]
