# Generated by Django 5.2.7 on 2025-11-09 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0010_merge_manual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-created_at",),
                "permissions": (
                    ("view_all_messages", "Может просматривать все сообщения"),
                ),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                help_text="Основное содержимое письма в свободной форме.",
                verbose_name="Текст письма",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь-владелец шаблона сообщения.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["owner"], name="idx_message_owner"),
        ),
    ]
