# Generated by Django 5.2.7 on 2025-11-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0011_add_owner_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь-владелец шаблона сообщения.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
