services:
  db:
    image: postgres:16-alpine
    container_name: message_autosend_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: message_autosend_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - appnet

  web:
    build:
      context: .
    container_name: message_autosend_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - appnet

  worker:
    build:
      context: .
    container_name: message_autosend_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
    command: >
      sh -c "celery -A config worker -l INFO"
    networks:
      - appnet

  beat:
    build:
      context: .
    container_name: message_autosend_beat
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
    command: >
      sh -c "celery -A config beat -l INFO"
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: message_autosend_nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    networks:
      - appnet

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  appnet:
    driver: bridge