# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Уникальный адрес получателя (будет приведён к нижнему регистру).",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Полное имя получателя.",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, message="Минимум 2 символа."
                            )
                        ],
                        verbose_name="Ф. И. О.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о получателе (необязательно).",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи.",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи.",
                        verbose_name="Обновлено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ("full_name", "email"),
                "permissions": (("view_all_recipients", "Может просматривать всех получателей"),),
            },
        ),
    ]
