# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь-владелец карточки клиента.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["owner"], name="idx_recipient_owner"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["email"], name="idx_recipient_email"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["full_name"], name="idx_recipient_fullname"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["-created_at"], name="idx_recipient_created_desc"),
        ),
    ]
