# Generated by Django 5.2.7 on 2025-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Обновлено",
            ),
        ),
    ]
