# Generated by Django 5.2.7 on 2025-11-07 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_recipient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ("full_name", "email"),
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация о получателе (необязательно).",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Уникальный адрес получателя (будет приведён к нижнему регистру).",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(
                help_text="Полное имя получателя.",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Минимум 2 символа."
                    )
                ],
                verbose_name="Ф. И. О.",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи.",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["email"], name="idx_recipient_email"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["full_name"], name="idx_recipient_fullname"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(
                fields=["-created_at"], name="idx_recipient_created_desc"
            ),
        ),
    ]
