# Generated by Django 5.2.7 on 2025-11-09 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_merge_manual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ("full_name", "email"),
                "permissions": (
                    ("view_all_recipients", "Может просматривать всех получателей"),
                ),
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["owner"], name="idx_recipient_owner"),
        ),
    ]
