# Generated by Django 5.2.7 on 2025-10-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(verbose_name="Дата/время первой отправки"),
                ),
                ("end_at", models.DateTimeField(verbose_name="Дата/время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Заполняется после первой реальной отправки.",
                        null=True,
                        verbose_name="Последняя отправка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mailings",
                        to="messages_app.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="mailings",
                        to="clients.recipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("-created_at",),
            },
        ),
    ]
