# Generated by Django 5.2.7 on 2025-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(verbose_name="Дата/время первой отправки"),
                ),
                ("end_at", models.DateTimeField(verbose_name="Дата/время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        help_text="Авторассчитывается при сохранении (см. compute_status()).",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ставитcя после первой реальной отправки.",
                        null=True,
                        verbose_name="Последняя отправка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("-start_at", "-id"),
                "permissions": (
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("disable_mailing", "Может отключать (завершать) рассылки"),
                ),
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата/время попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(blank=True, verbose_name="Ответ почтового сервера"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор инициатора (обычно email пользователя).",
                        max_length=150,
                        null=True,
                        verbose_name="Кем запущено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ("-attempted_at",),
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "recipient",
                    models.CharField(max_length=254, verbose_name="Кому (email)"),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Например: SENT, ERROR, SKIPPED, DRY_RUN.",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="Детали")),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор инициатора (обычно email пользователя).",
                        max_length=150,
                        null=True,
                        verbose_name="Кем запущено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправок",
                "ordering": ("-created_at",),
            },
        ),
    ]
