# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mailings",
                to="messages_app.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
