# Generated by Django 5.2.7 on 2025-10-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "recipient",
                    models.CharField(max_length=254, verbose_name="Кому (email)"),
                ),
                ("status", models.CharField(max_length=32, verbose_name="Статус")),
                ("detail", models.TextField(blank=True, verbose_name="Детали")),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Кем запущено",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправок",
                "ordering": ("-created_at",),
            },
        ),
    ]
