# Generated by Django 5.2.7 on 2025-11-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("mailings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь-владелец этой рассылки.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Кому отправляем.",
                related_name="mailings",
                to="clients.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status"], name="idx_mailing_status"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["start_at"], name="idx_mailing_start"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["end_at"], name="idx_mailing_end"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["-created_at"], name="idx_mailing_created_desc"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["owner"], name="idx_mailing_owner"),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="mailing_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["mailing", "-attempted_at"], name="idx_attempt_mailing_last"
            ),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(fields=["status"], name="idx_attempt_status"),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["triggered_by"], name="idx_attempt_triggered_by"
            ),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(
                fields=["mailing", "-created_at"], name="idx_log_mailing_created"
            ),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["status"], name="idx_log_status"),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["recipient"], name="idx_log_recipient"),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["triggered_by"], name="idx_log_triggered_by"),
        ),
    ]
