# Generated by Django 5.2.7 on 2025-11-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailinglog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="status",
            field=models.CharField(
                help_text="Например: SENT, ERROR, SKIPPED, DRY_RUN.",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата/время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ("-attempted_at",),
                "indexes": [
                    models.Index(
                        fields=["mailing", "-attempted_at"],
                        name="mailings_ma_mailing_43d49d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="mailings_ma_status_c690eb_idx"
                    ),
                ],
            },
        ),
    ]
