# Generated by Django 5.2.7 on 2025-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_recipient_options_alter_recipient_comment_and_more"),
        ("mailings", "0003_alter_mailinglog_status_mailingattempt"),
        ("messages_app", "0002_alter_message_body_alter_message_subject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-start_at", "-id"),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameIndex(
            model_name="mailingattempt",
            new_name="idx_attempt_mailing_last",
            old_name="mailings_ma_mailing_43d49d_idx",
        ),
        migrations.RenameIndex(
            model_name="mailingattempt",
            new_name="idx_attempt_status",
            old_name="mailings_ma_status_c690eb_idx",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Список адресатов рассылки.",
                related_name="mailings",
                to="clients.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                help_text="Текущий статус рассылки (автообновляется при сохранении).",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status"], name="idx_mailing_status"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["start_at"], name="idx_mailing_start"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["end_at"], name="idx_mailing_end"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["-created_at"], name="idx_mailing_created_desc"),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(
                fields=["mailing", "-created_at"], name="idx_log_mailing_created"
            ),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["status"], name="idx_log_status"),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["recipient"], name="idx_log_recipient"),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="mailing_end_after_start",
            ),
        ),
    ]
