# Generated by Django 5.2.7 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_recipient_options_alter_recipient_comment_and_more"),
        ("mailings", "0004_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="triggered_by",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор инициатора (обычно email пользователя).",
                max_length=150,
                null=True,
                verbose_name="Кем запущено",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Ставитcя после первой реальной отправки.",
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Кому отправляем.",
                related_name="mailings",
                to="clients.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                help_text="Авторассчитывается при сохранении (см. compute_status()).",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="triggered_by",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор инициатора (обычно email пользователя).",
                max_length=150,
                null=True,
                verbose_name="Кем запущено",
            ),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["triggered_by"], name="idx_attempt_triggered_by"
            ),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(fields=["triggered_by"], name="idx_log_triggered_by"),
        ),
    ]
