# Generated by Django 5.2.7 on 2025-11-09 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0017_owner_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-start_at", "-id"),
                "permissions": (
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("disable_mailing", "Может отключать (завершать) рассылки"),
                ),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь-владелец этой рассылки.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
