# Generated by Django 5.2.7 on 2025-11-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0018_add_owner_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь-владелец этой рассылки.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
